### ISSUE TITLE
Menu for Enabled vs Disabled Pages with Submenus

### ISSUE THREAD

**Issue by jncraig** [nvisionative/nvQuickTheme#148] opened 2019-03-29 03:44 UTC
## Describe the bug
If a page is enabled for navigation and has subpages, there is a separation between the page name and the down arrow.

if a page is disabled for navigation and has subpages, there is no separation.

## To Reproduce
Go to a page with children, and disable the page for navigation.  The separator disappears when the page is reloaded.

## Expected behavior
The menu entries should look the same.  There should not be a hand pointer for disabled pages.

(Note that when the separator appears, the page name and the down arrow have different mouseover characteristics, too.)

## Errors
Paste the error(s) related to this issue.

## Additional context

![image](https://user-images.githubusercontent.com/4732485/55208109-5515d200-51b3-11e9-9cdb-bab18dfced4b.png)

**Comment by Tychodewaard** [comment] 2019-04-24 19:18
This is as intended, AFAIK.
If the top level (or any other) is active, you should be able to get to that page by clicking or tapping. But you should also be able to get to pages on sub level by hovering or tapping. That's why there are 2 parts in the button.

If the toplevel is disabled, this is done because it is just a gateway to sublevel and the toplevel has no actual content. So, the ux does not require 2 functions but just one: show me the sub level.

**Comment by jncraig** [comment] 2019-04-24 23:48
I understand that, but ... if the top level is disabled, can't hovering
over the button show the dropdowns?  If the top is enabled, hovering over
the button part can also show the dropdowns.

I suppose I can always modify the menu to do that.  I have that kind of
behavior on another site, and change the hand to a pointer and vice versa
depending on enebled/disabled.  That makes more sense to me.  So, maybe
modifying the menu is the way to go.  I could even post it back as an
alternative.

**Comment by nvisionative** [comment] 2019-04-25 18:25
@jncraig the way it is implemented by default is the intended implementation and is the "standard" (common) UX for this type of split menu.  This is mainly for mobile (touch) devices so that there is a clear distinction between actions to "expanding the menu" versus "visiting a page".  When a page is disabled and has subs, there is only one action for the disabled page (expand the menu) versus two, so there is no need for a split button.

That said, there is no problem in replacing this with an experience you believe better suits your client's or your needs.  We do that all the time for our client sites.  😉 

We'll go ahead and close this issue out since there are no specific changes to be made to the base starting point.  Thanks for the dialog!

**Closed by nvisionative** 2019-04-25 18:25 UTC
Labels: question

**Comment by jncraig** [comment] 2019-04-25 18:36
👆
