### ISSUE TITLE
Import Bootstrap and include in SASS compilation, so variable names, mix-ins, etc can be used/extended

### ISSUE THREAD

**Issue by iJungleboy** [nvisionative/nvQuickTheme#26] opened 2018-05-24 15:02 UTC
Bootstrap 4 has a lot of variable conventions, like `$primary` for the primary color (I think it used to be `$brand-primary` or something in BS3). 

The 2sxc-content-templates are set up to take any "standard" bootstrap4 theme - so you can run SASS on them and rebuild all the content-element styles. But this theme uses other names, like `$primary-color` or `$light-grey` (which should be `$gray-100` or `$gray-200` if you use the bootstrap 4 conventions).

It would be good, if these variable names would be the same as the bootstrap conventions.

**Comment by john-Graham** [comment] 2018-05-24 15:03
Agreed.   was confused by that just yesterday.

**Comment by nvisionative** [comment] 2018-05-24 16:18
@iJungleboy and @john-Graham - thanks.  **nvQuickSite** usese Bootstrap 4 in its out-of-box state, so you are welcome to use anything that is used in Bootstrap.  The variables you are referring to are custom theme variables.  @tksheppard may have more insight into this, but the intent were for these to be treated separately for maximum flexibility in theme creation.  Please keep in mind that nvQuickTheme is used to develop themes for sites regardless of their use of Bootstrap, 2sxc, etc.

**Comment by iJungleboy** [comment] 2018-05-24 18:42
The core idea of sticking to the default SASS variables is that they are the convention in bootstrap 4, so the more components use it, the flatter the learning curve, because you just know (by convention) which variable is used. 

If you use other variable names for the default purpose, then the default variables will contain the "wrong" value - namely not the one you are using. Since the skin is usually the "master" in terms of design, components can only re-use this if the skins SASS variables use the convention. 

So let's say any part wants to use a color that's 90% the primary color. That's what SASS would let you do, but on this skin it won't work, because $primary was left at the default and doesn't contain the real primary color. Make sense?

**Comment by john-Graham** [comment] 2018-05-24 18:47
Agreed.   Part of the issue is that the naming is so similar.   I wouldn't have gotten confused  if the class names and sass variables for the theme itself were prefixed.  Like $nvPrimary-color and $nvLight-Grey . 

It's mostly about being able to quickly differentiate the fact that you're working with variables for bootstrap vs variables for the nvQuickTheme

**Comment by tksheppard** [comment] 2018-05-24 18:58
Curiosity from myself, would you gentlemen find more usefulness with more differentiated variable names, or with a full integration with the Bootstrap SCSS, and essentially removing the need for most 'nvVariables'?  The only downside I see here is we've tried to keep it fairly simple, and Bootstrap 4's variables.scss is daunting for someone who doesn't know SCSS.

**Comment by iJungleboy** [comment] 2018-05-24 19:04
I'm fully for using default variables only, unless new ones are needed. Everything else is very confusing and doesn't scale when working with other components. 

I understand the issue trying to get people to use it who don't know SASS. I would approach it differently. 

1. First of all, if they do enter SASS with this theme, it would actually be better if they knew the normal convention, than a derivative. 
2. second: if you use the standard names, your documentation will look the same, as you'll only mention variables that you use - not mentioning all the other ones. so I don't think it will be harder to start
3. third: when you use standard variables, you can always refer to other documentation where needed...
4. fourth: standard variables are also great when people try to do something and google the term - because they will find StackOverflow answers related to that variable

So I'm all for 100% standard if reasonably possible :)

**Comment by tksheppard** [comment] 2018-05-24 19:35
That's probably the approach I would take. I would pull out specific variables within Bootstrap that I feel are frequently changed variables, and keep them within nvQuickTheme's SASS, but since the two wouldn't be mutually exclusive, I can easily set the priorities correctly. This way any calls to those variables would run through correctly in both Bootstrap and nvQT. That's already what I've been attempting to do, I've just been putting off doing all the shifting required to fully implement Bootstrap 4's SASS.

**Comment by iJungleboy** [comment] 2018-05-24 20:47
I think that would be great. 

Just in case you may not know SASS `!default` please look into that too. It's one of the things that make life much easier in complex environments - https://robots.thoughtbot.com/sass-default

basically it's for saying `$myvar` should be 7, unless it's already defined, then keep the original. So it's kind of a "make sure this variable has a value if it doesn't exist yet"

I'm not sure if you'll need it, but I thought I would mention it because we use it a lot in our solution https://github.com/2sic/dnn-theme-bootstrap4-instant/blob/master/src/_variables.scss

our model is "show all values - but actually use the default, unless you really want to set something, then remove the !default flag. But I believe your model of "show only the changed values" will be easier to understand for beginners.

**Comment by nvisionative** [comment] 2018-05-25 17:15
Great dialog everyone.  This also brings back an internal conversation we have been having off and on throughout the development of nvQuickTheme.  We want to ultimately be more decoupled from the CSS framework, allowing easy switching out of Bootstrap for another CSS framework (e.g., Foundation, etc.).  However, the challenge is the "easy switching out" part.  We have achieved a somewhat loose coupling, but we admit we are not where we ultimately want to be with this.  I bring this up because it seems to be relevant in light of this conversation.  Additional thoughts on this are surely welcome!

**Comment by iJungleboy** [comment] 2018-06-06 07:09
Note that we'll change our gulp within a few days to add minification and separate map files.

**Comment by nvisionative** [comment] 2019-03-13 16:20
After the dust has settled with the 2.0.0 release, we are now ready to implement our solution related to this issue.  This will most likely be included in the 2.1.0 release and follows the recommendation by @john-Graham.  Now that Bootstrap is no longer within our **src** folder, this will be a simple change to **gulpfile.js**.  We would update to no longer keep Bootstrap separate in the output.  We would instead combine Bootstrap (still from **node_modules**) in our Sass compilation of **src**.  This will allow ease of overriding Bootstrap variables and will also allow the use of Bootstrap mixins within **src** SCSS files.  **Font Awesome** and **normalize.css** would still be kept separate.  Thanks to everyone for chiming in on this issue and helping to guide the project to a better solution for DNN theme developers!

**Comment by iJungleboy** [comment] 2019-03-14 07:20
This is very cool - best practice! Awesome!

**Comment by david-poindexter** [comment] 2019-07-07 01:48
Closing per #171

**Closed by david-poindexter** 2019-07-07 01:48 UTC
Labels: enhancement
